### PR TITLE
Added base for active window grabber 

### PR DESCRIPTION
**Pull request by JasperSmitz**
Basic implementation of the active window grabber. Simply reports to console when the active window changes.

### CODE REVIEW

**Review by RainbowNova — CHANGES_REQUESTED** [review]
Couple of notes:

1. The functions returns nothing. Eventually it'll need to return the active window, as per the function name.
2. Why did you put a function call in main()? 
3. While True ==> Rianne would be very big disappointed :(
4. A while loop is not needed within the function, as the function itself will eventually be called in a while loop in monitorings_software.py. 

- Keano

**Review by RainbowNova — CHANGES_REQUESTED** [review]
Denied.

The "last_active_window = active_window" variable does not get returned by the function, so it won't be 'remembered' or saved. Meaning when the loop within 'monitorings_software.py' calls the function again, 'if active_window != last_active_window:' will always return True since last_active_window will be forgotten every single time.

- Love, Keano

**Comment by JasperSmitz** [comment]
It works 🙏 trust

**Review by RainbowNova — APPROVED** [review]
Denied.

Looks good to me 👍 

- Love, Keano

**Pull request merged**
